---
title: "class"
author: "George Guarnieri"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(skimr)
library(fs)

download.file('https://github.com/TheUpshot/2018-live-poll-results/archive/master.zip', destfile = 'master.zip')

unzip('master.zip')

first_poll<-read_csv('2018-live-poll-results-master/data/elections-poll-az02-1.csv',col_types = cols(
  .default = col_character(),
  turnout_scale = col_double(),
  turnout_score = col_double(),
  w_LV = col_double(),
  w_RV = col_double(),
  final_weight = col_double(),
  timestamp = col_datetime(format = "")
))

skim(first_poll)

files<-list.files(path='2018-live-poll-results-master/data')

my_list <- dir_ls('2018-live-poll-results-master/data/')
my_list

raw<-map_dfr(my_list,.id='source',~read_csv(.x),col_types = cols(
  .default = col_character(),
  turnout_scale = col_double(),
  turnout_score = col_double(),
  w_LV = col_double(),
  w_RV = col_double(),
  final_weight = col_double(),
  timestamp = col_datetime(format = "")
))

raw

skim(raw)
glimpse(raw)
summary(raw)

#dem vote and gender

cleaned <- raw %>%
  mutate(dvote=ifelse(response=='Dem',1,0)) %>%
  mutate(female=ifelse(gender=='Female',1,0)) %>%
  select(dvote,female, response, gender) %>% 
  mutate(predict = predict.glm(glm_obj, newdata = cleaned, type = c("response")))

cleaned

lm_obj <- lm(formula=dvote~female, data=cleaned)

glm_obj <- glm(formula=dvote~female, data=cleaned, family = "binomial")

glm_obj

ggplot(lm_obj, aes(x = female, y = dvote))  +
  geom_jitter(height = 0.1,
              width = .1,
              alpha = .05) +
  geom_smooth(method = 'lm',
              method.args = list(family = 'binomial'))

my_data <- tibble(female = c(0, 0, 1)) %>% 
  mutate(predict = predict.glm(glm_obj, newdata = my_data, type = c("response")))

predict.glm(glm_obj, newdata = my_data, type = c("response"))

my_data 

cleaned %>% 
  group_by(dvote) %>% 
  summarise(avg = mean(predict))

```

